Add build events
JustArchiNET/ASF-PluginTemplate pull request #10
Opened 2022-05-27 15:06 UTC by chr233

Auto copy plugin file to ASF's plugins folder after build.

## Pull request

2022-05-27 15:12 UTC, chr233 commented
I'd better skip exec when in ci

2022-05-27 15:54 UTC, chr233 commented
Now use copy task instead of exec

2022-05-27 16:07 UTC, JustArchi requested changes
See CI failure,

2022-05-27 16:07 UTC, JustArchi commented on MyAwesomePlugin/MyAwesomePlugin.csproj
> +			DestinationFolder="$(SolutionDir)ArchiSteamFarm\ArchiSteamFarm\bin\$(Configuration)\$(TargetFramework)\plugins\"
See CI failure, I didn't test this but I don't see why it shouldn't work. Current path should be relative to `csproj`, we use the same trick above for project reference.

```suggestion
			DestinationFolder="..\ArchiSteamFarm\ArchiSteamFarm\bin\$(Configuration)\$(TargetFramework)\plugins\"
```

2022-05-27 16:35 UTC, chr233 commented
Why this time passed 🤔

2022-05-27 16:35 UTC, JustArchi approved these changes
LGTM, initially I wanted to limit to to debug builds only but I don't see a good reasoning, developer might want to test both configurations.

2022-05-27 16:59 UTC, Abrynos approved these changes
Works as intended.

2022-05-27 16:59 UTC, Abrynos commented on MyAwesomePlugin/MyAwesomePlugin.csproj
> +			DestinationFolder="..\ArchiSteamFarm\ArchiSteamFarm\bin\$(Configuration)\$(TargetFramework)\plugins\"
I personally would use slashes instead of backslashes, but this is fine.

Edit: I just took a look and it seems the only (C# related) files in the whole JustArchiNET organisation that use forward slashes for paths are `Directory.Build.props` files. Please ignore this comment.

2022-05-27 17:27 UTC, ezhevita approved these changes

2022-05-27 18:13 UTC, JustArchi commented
Thank you for your contribution @chr233! :trophy:

2022-05-27 18:13 UTC, merged

2022-06-25 09:56 UTC, Ryzhehvost commented
Does not work when ASF is in release configuration, and plugin is in debug configuration (and that's the only sane combination if you ask me).
![image](https://user-images.githubusercontent.com/15903022/175768525-616e530c-ed96-47c3-a3c8-8689d87a1cbb.png)

2022-06-25 10:07 UTC, Abrynos commented
I tend to disagree. What benefit do you have from building ASF in release configuration? If any, I'd recommend the `DebugFast` configuration for it, because it disables most static code analysis and therefore leads to much faster compile time in case you modify ASF for debugging purposes. 😅

2022-06-25 10:14 UTC, Ryzhehvost commented
Benefit is obvious - when built in debug configuration, ASF enables debug logging, which clutters log output to the level of being unusable. And I want to see log messages from my plugin, if there are any. On the contrary, building ASF in debug mode does not have any benefits, since we are debugging plugin, not ASF.

2022-06-25 10:20 UTC, Abrynos commented
> since we are debugging plugin, not ASF.

It happened to me more than once that debugging a plugin lead to debugging ASF itself. The most recent instance even lead to [changes in ASF](https://github.com/JustArchiNET/ArchiSteamFarm/commit/0eab63bab5fbcf3bc462bf640cca5c2d30b1aa90).

2022-06-25 10:40 UTC, Ryzhehvost commented
Ok, you've got me. My configuration is not the **only** sane configuration, it's just what you want in most cases, while debug/debug being rarely needed (I'm unsure if ever needed it with any of my plugins).

2022-06-25 10:45 UTC, Abrynos commented
You can always extend the `PostBuild` target in your `.csproj` file with more `<Copy .../>` directives. I for one prefer the plugin and ASF using the same build configuration.

2022-06-25 11:31 UTC, JustArchi commented
You can disable debug logging if you want to @Ryzhehvost, ASF *still* reads `NLog.config`, the only difference is that debug configuration by default enables more of it to aid debugging.

I disagree with your statement, since debug build of ASF is equally important so you can set breakpoints directly in ASF code and see what exactly is happening in case something doesn't work as you expect from your plugin side. Just because it's not always needed isn't an argument to me, you could say the same about coding in notepad since you don't need debugger at all.

Therefore yes, I believe Debug/Debug and Release/Release are sane configurations because they have a particular purpose, in which first one is used for development, testing, debugging and understanding stuff better, and second one for publishing as well as ensuring your code works properly with additional optimizations and analysis that happens in release builds. If you require/want other mixes of configuration, nothing is stopping you from adding event yourself, but adding it by default into plugin template is not justified imho.

2022-06-25 19:53 UTC, Ryzhehvost commented
Publishing from Visual studio? Terrible idea. And Debug/Debug makes development, testing and debugging **harder** than Release/debug. If you've developed at least tenth of plugins I did - you would know this.
Adding NLog.config to every project I plan to debug is also not very best idea. It's more a hack than a solution.
Right now build events work just wrong, since they put build result to wrong folder. If they don't work as intended - why are they even there?

2022-06-26 06:29 UTC, Abrynos commented
> Publishing from Visual studio? Terrible idea.

I absolutepy agree.

> Right now build events work just wrong, since they put build result to wrong folder. If they don't work as intended - why are they even there?

I believe they do work as intended. Just your intention/expectation is different from ours. Sadly I do not believe there is a nice way to make everyone happy here 🙁

2022-06-27 09:15 UTC, Ryzhehvost commented
I would recommend doing something like this:
```
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="..\ArchiSteamFarm\ArchiSteamFarm\bin\Release\$(TargetFramework)\plugins\$(AssemblyName)\" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="..\ArchiSteamFarm\ArchiSteamFarm\bin\Debug\$(TargetFramework)\plugins\$(AssemblyName)\" SkipUnchangedFiles="true" />
	</Target>
```
cons:
- it puts output file to a wrong place (same as current solution)

pros: 
- it also puts file to a correct place (unlike current solution)
- puts a file in a separate folder (may be useful if plugin will create it's own files for storage, etc...)