Get rid of ad-m/github-push-action
JustArchiNET/ASF-PluginTemplate pull request #28
Opened 2024-09-15 14:21 UTC by Rudokhvist

## Pull request

## Changes

I removed **ad-m/github-push-action**, because it causes issues in private github repositories (at least for me), but I believe this change is also good because it removes unnecessary layers of abstraction and dependency upon additional reusable action made by third party, so it should improve both performance and security. 
I tested it in my private repo, and it seems to work as intended.
Please consider merging this pull request.

2024-09-15 17:03 UTC, JustArchi commented
Do we need that safe.directory? Shouldn't the user be the same for whole process?

2024-09-15 17:07 UTC, Rudokhvist commented
> Do we need that safe.directory? Shouldn't the user be the same for whole process?

For some reason push don't work without that. I'm not that good in git, so I just did what git adviced to do. If you know a better way, I will gladly change that. But from what I understand, setting dir as safe in a workflow shouldn't be a security flaw.

2024-09-15 17:12 UTC, JustArchi commented
There is no safe.directory call in https://github.com/ad-m/github-push-action/blob/master/start.sh :thinking:

2024-09-15 17:13 UTC, Rudokhvist commented
Maybe that's why it don't work for private repo? I dunno.

2024-09-15 17:16 UTC, Rudokhvist commented
A bit of background:
![image](https://github.com/user-attachments/assets/ba2e8847-2c90-40a7-a598-711cc3aabcbb)

2024-09-15 17:21 UTC, JustArchi commented
What are the logs of ad-m action?

2024-09-15 17:23 UTC, Rudokhvist commented
They are not really helpful
![image](https://github.com/user-attachments/assets/0d896985-4c68-44e4-8dea-0a554f3db352)

2024-09-15 19:52 UTC, JustArchi commented
It seems it's the same issue: https://github.com/ad-m/github-push-action/issues/123

Could you perhaps keep the safe.directory change but revert back to using an action?

The action does a bit more than `git push`, in particular it detects the situation the repo is in and specifies explicitly remote repo and target branch, something that I'd prefer not to do myself and using `git push` without args risks doing things wrong as soon as you execute the action from a different context than the expected one.

This way it should fix the issue you have while not regressing in those edge cases compared to before.

2024-09-16 06:34 UTC, Rudokhvist commented
Just checked, and no, just adding safe dir is not enough, ad-m/github-push-action fails with same error.
If you strongly believe that just `git push` is not enough and this PR is harmful in som way, well, I guess we can just close this PR and keep it like it's now. I use edited workflows anyway, so it's not a big deal. I just thought that removing additional dependency would benefit all users.

2024-09-16 10:51 UTC, JustArchi commented
I don't have strong opinion about this, I remember I wanted to do it exactly the way you suggest and it didn't work back then, but perhaps things have changed since then.

2024-09-16 10:56 UTC, JustArchi requested changes

2024-09-16 10:56 UTC, JustArchi commented on .github/workflows/bump-asf-reference.yml
> +        git config --global --add safe.directory $(pwd)
```suggestion
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
```

2024-09-16 11:09 UTC, Rudokhvist commented
> I don't have strong opinion about this, I remember I wanted to do it exactly the way you suggest and it didn't work back then, but perhaps things have changed since then.

I guess the change lies in **actions/checkout** action that is used in this workflow https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token

2024-09-16 12:13 UTC, JustArchi approved these changes

2024-09-16 12:14 UTC, JustArchi commented
Considering the fact that checkout action itself talks about `git push`, I consider this good and safe enough for our use case.

Thanks! :trophy:

2024-09-16 12:14 UTC, merged